 const  nationalities = JSON.parse(
    `[
      {"name":"Ethiopia","arabicName":"إثيوبيــــا","code":"ETH"},
      {"name":"Aruba","arabicName":"آروبا","code":"ABW"},
      {"name":"Eritrea","arabicName":"أريتيريا","code":"ERI","isArabic":true},
      {"name":"Spain","arabicName":"أسبانيا","code":"ESP"},
      {"name":"Afghanistan","arabicName":"أفغانستان","code":"AFG","isMission":true},
      {"name":"Albania","arabicName":"ألبانيا","code":"ALB"},
      {"name":"Germany","arabicName":"ألمانيا","code":"DEU"},
      {"name":"Angola","arabicName":"أنجولا","code":"AGO"},
      {"name":"Anguilla","arabicName":"أنجويلا","code":"AIA"},
      {"name":"Indonesia","arabicName":"إندونسيا","code":"IDN","isMission":true},
      {"name":"Uruguay","arabicName":"أورجواى","code":"URY"},
      {"name":"Uganda","arabicName":"أوغندا","code":"UGA"},
      {"name":"Azerbaijan","arabicName":"اذربيجان","code":"AZE"},
      {"name":"Armenia","arabicName":"ارمينيا","code":"ARM"},
      {"name":"Australia","arabicName":"استراليا","code":"AUS"},
      {"name":"Estonia","arabicName":"استونيا","code":"EST"},
      {"name":"Ukraine","arabicName":"اكرانيا","code":"UKR"},
      {"name":"United Arab Emirates","arabicName":"الإمارات العربية المتحدة","code":"ARE","isArabic":true},
      {"name":"Argentina","arabicName":"الارجنتين","code":"ARG"},
      {"name":"Jordan","arabicName":"الاردن","code":"JOR","isArabic":true,"isMission":true},
      {"name":"Ecuador","arabicName":"الاكوادور","code":"ECU"},
      {"name":"Bahrain","arabicName":"البحرين","code":"BHR","isArabic":true},
      {"name":"Brazil","arabicName":"البرازيل","code":"BRA"},
      {"name":"Portugal","arabicName":"البرتغال","code":"PRT"},
      {"name":"Bosnia and Herzegovina","arabicName":"البوسنة","code":"BIH"},
      {"name":"Gabon","arabicName":"الجابون","code":"GAB"},
      {"name":"MONTENEGRO","arabicName":"الجبل الاسود","code":"MNE"},
      {"name":"Algeria","arabicName":"الجزائر","code":"DZA","isArabic":true,"isMission":true},
      {"name":"Dominican","arabicName":"الدمنيكان","code":"DMA"},
      {"name":"Denmark","arabicName":"الدنمارك","code":"DNK"},
      {"name":"Salvador","arabicName":"السلفادور","code":"SLV"},
      {"name":"Senegal","arabicName":"السنغال","code":"SEN"},
      {"name":"Sudan","arabicName":"السودان","code":"SDN","isArabic":true,"isMission":true},
      {"name":"Sweden","arabicName":"السويد","code":"SWE"},
      {"name":"Somalia","arabicName":"الصومال","code":"SOM","isArabic":true},
      {"name":"China","arabicName":"الصين","code":"CHN"},
      {"name":"Iraq","arabicName":"العراق","code":"IRQ","isArabic":true},
      {"name":"Vatican City","arabicName":"الفاتيكان","code":"VAT"},
      {"name":"Philippines","arabicName":"الفلبين","code":"PHL"},
      {"name":"Cameroon","arabicName":"الكاميرون","code":"CMR"},
      {"name":"Congo COG","arabicName":"الكنغو","code":"COG"},
      {"name":"Kuwait","arabicName":"الكويت","code":"KWT","isArabic":true},
      {"name":"Maldives","arabicName":"المالديف","code":"MDV"},
      {"name":"Hungary","arabicName":"المجر","code":"HUN"},
      {"name":"Morocco","arabicName":"المغرب","code":"MAR","isArabic":true,"isMission":true},
      {"name":"Mexico","arabicName":"المكسيك‏","code":"MEX"},
      {"name":"Kingdom Saudi Arabia","arabicName":"المملكة العربية السعودية","code":"SAU","isArabic":true},
      {"name":"United Kingdom","arabicName":"المملكة المتحدة","code":"GBR"},
      {"name":"Norway","arabicName":"النرويج","code":"NOR"},
      {"name":"Austria","arabicName":"النمسا","code":"AUT"},
      {"name":"Niger","arabicName":"النيجر","code":"NER","isMission":true},
      {"name":"India","arabicName":"الهند","code":"IND","isMission":true},
      {"name":"United States","arabicName":"الولايات المتحدة الامريكية","code":"USA"},
      {"name":"Japan","arabicName":"اليابان","code":"JPN"},
      {"name":"Yemen","arabicName":"اليمن","code":"YEM","isArabic":true,"isMission":true},
      {"name":"Greece","arabicName":"اليونان","code":"GRC"},
      {"name":"Antigua and Barbuda","arabicName":"انتيجوا و باربودا","code":"ATG"},
      {"name":"Andorra","arabicName":"اندورا","code":"AND"},
      {"name":"Uzbekistan","arabicName":"اوزبكستان","code":"UZB"},
      {"name":"Iran","arabicName":"ايران","code":"IRN"},
      {"name":"Ireland","arabicName":"ايرلاندا","code":"IRL"},
      {"name":"Iceland","arabicName":"ايسلاندا","code":"ISL"},
      {"name":"Italy","arabicName":"ايطاليا","code":"ITA"},
      {"name":"Papua New Guinea","arabicName":"بابوا - نيو - جونييا","code":"PNG"},
      {"name":"Paraguay","arabicName":"باراجواى","code":"PRY"},
      {"name":"Barbados","arabicName":"باربادوس","code":"BRB"},
      {"name":"Barbados","arabicName":"باربادوس","code":"BRD"},
      {"name":"Pakistan","arabicName":"باكستان","code":"PAK","isMission":true},
      {"name":"Palau","arabicName":"بالو","code":"PLW"},
      {"name":"Bermuda","arabicName":"برمودا","code":"BMU"},
      {"name":"Brunei","arabicName":"بروناى","code":"BRN"},
      {"name":"Belgium","arabicName":"بلجيكا","code":"BEL"},
      {"name":"Bulgaria","arabicName":"بلغاريا","code":"BGR"},
      {"name":"Belize","arabicName":"بليز","code":"BLZ"},
      {"name":"Bangladesh","arabicName":"بنجلاديش","code":"BGD"},
      {"name":"Panama","arabicName":"بنما","code":"PAN"},
      {"name":"Benin","arabicName":"بنين","code":"BEN"},
      {"name":"Bhutan","arabicName":"بوتان","code":"BTN"},
      {"name":"Botswana","arabicName":"بوتسوانا","code":"BWA"},
      {"name":"Puerto Rico","arabicName":"بورتوريكو","code":"PRI"},
      {"name":"Burkina Faso","arabicName":"بوركينا","code":"BFA"},
      {"name":"Burundi","arabicName":"بوروندى","code":"BDI"},
      {"name":"Poland","arabicName":"بولندا","code":"POL"},
      {"name":"Bolivia","arabicName":"بوليفيا","code":"BOL"},
      {"name":"French Polynesia","arabicName":"بولينيزيا الفرنسية","code":"PYF","isArabic":false},
      {"name":"Peru","arabicName":"بيرو","code":"PER"},
      {"name":"Belarus","arabicName":"بيلاروس","code":"BLR"},
      {"name":"Thailand","arabicName":"تايلاند","code":"THA","isMission":true},
      {"name":"Taiwan","arabicName":"تايوان","code":"TWN"},
      {"name":"Turkmenistan","arabicName":"تركمنستان","code":"TKM"},
      {"name":"Turkey","arabicName":"تركيا","code":"TUR","isMission":true},
      {"name":"Trinidad and tobago","arabicName":"ترينيداد وتوباجو","code":"TTO"},
      {"name":"Chad","arabicName":"تشاد","code":"TCD"},
      {"name":"Chile","arabicName":"تشيلي","code":"CHL"},
      {"name":"Tanzania","arabicName":"تنزانيا","code":"TZA"},
      {"name":"Togo","arabicName":"توجو","code":"TGO"},
      {"name":"Tuvalu","arabicName":"توفالــــــــو","code":"TUV"},
      {"name":"Tokelau","arabicName":"توكيلاو","code":"TKL"},
      {"name":"Tonga Islands","arabicName":"تونجــا","code":"TON"},
      {"name":"Tunisia","arabicName":"تونس","code":"TUN","isArabic":true,"isMission":true},
      {"name":"Jamaica","arabicName":"جامايكا","code":"JAM"},
      {"name":"Gambia","arabicName":"جامبيا","code":"GMB"},
      {"name":"Gibraltar","arabicName":"جبل طــــارق","code":"GIB"},
      {"name":"Green Land","arabicName":"جرين لاند","code":"GRL"},
      {"name":"Grenada","arabicName":"جرينادا","code":"GRD"},
      {"name":"Islands - Falkland","arabicName":"جزر - فوكلاند","code":"FLK"},
      {"name":"Bahamas","arabicName":"جزر البهاما","code":"BHS"},
      {"name":"Comoros Islands","arabicName":"جزر القمر","code":"COM","isArabic":true},
      {"name":"Turks and Caicos Islands","arabicName":"جزر تركس وكايكوس","code":"TCA"},
      {"name":"Solomon Islands","arabicName":"جزر سليمــــان","code":"SLB"},
      {"name":"US Virgin Islands","arabicName":"جزر فرجين","code":"VGB"},
      {"name":"British Virgin Islands","arabicName":"جزر فيرجينيا","code":"VIR"},
      {"name":"Cayman Islands","arabicName":"جزر كايمان","code":"CYM"},
      {"name":"Cook Islands","arabicName":"جزر كوك","code":"COK"},
      {"name":"Cocos Islands","arabicName":"جزر كوكوس","code":"CCK"},
      {"name":"Marshall Islands","arabicName":"جزر مارشال","code":"MHN"},
      {"name":"Marshall Islands","arabicName":"جزر مارشال","code":"MHL"},
      {"name":"Christmas Island","arabicName":"جزيرة كريسماس","code":"CXR"},
      {"name":"Norfolk Island","arabicName":"جزيرة نورفولك","code":"NFK"},
      {"name":"South Sudan","arabicName":"جمهوربة جنوب السودان","code":"SSD","isMission":true},
      {"name":"Czech Republic","arabicName":"جمهورية التشيك","code":"CZE"},
      {"name":"Dominican Republic","arabicName":"جمهورية الدمنيكان","code":"DOM"},
      {"name":"Slovakia","arabicName":"جمهورية سلوفاكيا","code":"SVK"},
      {"name":"Moldavia","arabicName":"جمهورية مالدوفا","code":"MDA"},
      {"name":"Central African Republic","ArabicName":"جمهورية وسط أفريقيا","code":"CAF"},
      {"name":"South Africa","arabicName":"جنوب أفريقيا","code":"ZAF","isMission":true},
      {"name":"Guatemala","arabicName":"جواتيمالا","code":"GTM"},
      {"name":"Guam","arabicName":"جوام","code":"GUM"},
      {"name":"French Guiana","arabicName":"جوانا الفرنسية","code":"GUF"},
      {"name":"Georgia","arabicName":"جورجيا","code":"GEO"},
      {"name":"Guyana","arabicName":"جويانا","code":"GUY"},
      {"name":"Djibouti","arabicName":"جيبوتى","code":"DJI","isArabic":true},
      {"name":"Rwanda","arabicName":"روانــــــــــدا","code":"RWA"},
      {"name":"Russia","arabicName":"روسيا الإتحادية","code":"RUS"},
      {"name":"Romania","arabicName":"رومانيا","code":"ROU"},
      {"name":"Democratic Republic of Congo","arabicName":"جمهورية الكونغو الديمقراطية","code":"COD"},
      {"name":"Zambia","arabicName":"زامبيا","code":"ZMB"},
      {"name":"Zimbabwe","arabicName":"زيمبابوى","code":"ZIM"},
      {"name":"Western Samoa","arabicName":"ساموا","code":"WSM"},
      {"name":"American Samoa","arabicName":"ساموا الأمريكية","code":"ASM"},
      {"name":"San Marino","arabicName":"سان مارينو","code":"SMR"},
      {"name":"St. Lucia","arabicName":"ســانت لوتشــيا","code":"LCA"},
      {"name":"Sri Lanka","arabicName":"سريلانكا","code":"LKA"},
      {"name":"Slovenia","arabicName":"سلوفينيا","code":"SVN"},
      {"name":"Singapore","arabicName":"سنغافورة","code":"SGP"},
      {"name":"Swaziland","arabicName":"سوازيـلانـــــــــد","code":"SWZ"},
      {"name":"Syria","arabicName":"سوريا","code":"SYR","isArabic":true,"isMission":true},
      {"name":"Suriname","arabicName":"سورينام","code":"SUR"},
      {"name":"Switzerland","arabicName":"سويسرا","code":"CHE"},
      {"name":"Sierra Leone","arabicName":"سيراليون","code":"SLE"},
      {"name":"Seychelles","arabicName":"سيشل","code":"SYC"},
      {"name":"East Timor","arabicName":"شرق تيمور","code":"TMP"},
      {"name":"Serbia","arabicName":"صربيا","code":"SRB"},
      {"name":"Tajikistan","arabicName":"طاجكستان","code":"TJK"},
      {"name":"Ghana","arabicName":"غانـا","code":"GHA"},
      {"name":"Guinea","arabicName":"غينيا","code":"GIN"},
      {"name":"Equatorial Guinea","arabicName":"غينيا الأستوائية","code":"GNQ"},
      {"name":"Guinea Bissau","arabicName":"غينيا بيساو","code":"GNB"},
      {"name":"Vanuatu","arabicName":"فانواتو","code":"VUT"},
      {"name":"France","arabicName":"فرنسا","code":"FRA"},
      {"name":"Palestine","arabicName":"فلسطين","code":"PSE","isArabic":true,"isMission":true},
      {"name":"Venezuela","arabicName":"فنزويلا","code":"VEN"},
      {"name":"Finland","arabicName":"فنلاندا","code":"FIN"},
      {"name":"Fiji","arabicName":"فيجــــــى","code":"FJI"},
      {"name":"Vietnam","arabicName":"فييتنام","code":"VNM"},
      {"name":"Cyprus","arabicName":"قبرص","code":"CYP"},
      {"name":"Kyrgyzstan","arabicName":"قرغيزستان","code":"KGZ"},
      {"name":"Qatar","arabicName":"قطر","code":"QAT","isArabic":true},
      {"name":"Cape Verde Islands","arabicName":"كاب فيرد","code":"CPV"},
      {"name":"Kazakhstan","arabicName":"كاذاخستان","code":"KAZ"},
      {"name":"Cambodia","arabicName":"كامبوديا","code":"KHM"},
      {"name":"Croatia","arabicName":"كرواتيا","code":"HRV"},
      {"name":"Canada","arabicName":"كندا","code":"CAN"},
      {"name":"Cuba","arabicName":"كوبا","code":"CUB"},
      {"name":"Cote Divoire","arabicName":"كوت دي فوار","code":"CIV","isMission":true},
      {"name":"South Korea","arabicName":"كوريا الجنــوبية","code":"KOR"},
      {"name":"North Korea","arabicName":"كوريا الشمالية","code":"PRK"},
      {"name":"Costa Rica","arabicName":"كوستاريكا","code":"CRI"},
      {"name":"Kosovo","arabicName":"كوسوفا","code":"RKS"},
      {"name":"Colombia","arabicName":"كولومبيا","code":"COL"},
      {"name":"Kiribati","arabicName":"كيريباتيا","code":"KIR"},
      {"name":"Kenya","arabicName":"كينيا","code":"KEN"},
      {"name":"Latvia","arabicName":"لاتفيا","code":"LVA"},
      {"name":"Laos","arabicName":"لاوس","code":"LAO"},
      {"name":"Lebanon","arabicName":"لبنان","code":"LBN","isArabic":true},
      {"name":"Lithuania","arabicName":"لتوانيا","code":"LTU"},
      {"name":"Luxembourg","arabicName":"لوكسمبورج","code":"LUX"},
      {"name":"Libya","arabicName":"ليبيا","code":"LBY","isArabic":true},
      {"name":"Liberia","arabicName":"ليبيريا","code":"LBR","isMission":true},
      {"name":"Lesotho","arabicName":"ليسوتو","code":"LSO"},
      {"name":"Macau","arabicName":"ماكاو","code":"MAC"},
      {"name":"Macedonia","arabicName":"ماكيدونيا","code":"MKD"},
      {"name":"Malawi","arabicName":"مالاوى","code":"MWI"},
      {"name":"Malta","arabicName":"مالطا","code":"MLT"},
      {"name":"Mali","arabicName":"مالى","code":"MLI","isMission":true},
      {"name":"Malaysia","arabicName":"ماليزيا","code":"MYS","isMission":true},
      {"name":"Mayotte","arabicName":"مايوت","code":"MYT"},
      {"name":"Madagascar","arabicName":"مدغـشقر","code":"MDG"},
      {"name":"Egypt","arabicName":"مصر","code":"EGY","isArabic":true,"isMission":true},
      {"name":"Mongolia","arabicName":"منغوليا","code":"MNG"},
      {"name":"Mauritania","arabicName":"موريتانيا","code":"MRT","isArabic":true,"isMission":true},
      {"name":"Mauritius","arabicName":"موريشيوس","code":"MUS"},
      {"name":"Mozambique","arabicName":"موزمبيق","code":"MOZ"},
      {"name":"Monaco","arabicName":"موناكو","code":"MCO"},
      {"name":"Montserrat","arabicName":"مونتسرات","code":"MSR"},
      {"name":"Myanmar","arabicName":"مينمار","code":"MMR"},
      {"name":"Namibia","arabicName":"نامبيا","code":"NAM"},
      {"name":"Nauru","arabicName":"ناورو","code":"NRU"},
      {"name":"Nepal","arabicName":"نيبال","code":"NPL"},
      {"name":"Nigeria","arabicName":"نيجيريا","code":"NGA","isMission":true},
      {"name":"Nicaragua","arabicName":"نيكاراجوا","code":"NIC"},
      {"name":"New Caledonia","arabicName":"نيو - كاليدونيا","code":"NCL"},
      {"name":"New Zealand","arabicName":"نيوزيلاند","code":"NZL"},
      {"name":"Niue","arabicName":"نيوى جزر","code":"NIU"},
      {"name":"Haiti","arabicName":"هايتى","code":"HTI"},
      {"name":"Honduras","arabicName":"هندوراس","code":"HND"},
      {"name":"Netherlands","arabicName":"هولندا","code":"NLD"},
      {"name":"St. Helena","arabicName":"هيلينا","code":"SHN"},
      {"name":"Yugoslavia","arabicName":"يوغسلافيا","code":"YUG"},
      {"name":"Reunion","arabicName":"ريونيون", "code": "REU"},
      {"name":"Zimbabwe ZWE","arabicName":"زمبابوي","code":"ZWE"},
      {"name":"United Kingdom GBO","arabicName":"المملكة المتحدة","code":"GBO"},
      {"name":"United Kingdom GBD","arabicName":"المملكة المتحدة","code":"GBD"},
      {"name":"United Kingdom GBS","arabicName":"المملكة المتحدة","code":"GBS"},
      {"name":"United Kingdom GBP","arabicName":"المملكة المتحدة","code":"GBP"},
      {"name":"United Kingdom GBN","arabicName":"المملكة المتحدة","code":"GBN"},
      {"name":"Dominican DMA","arabicName":"جمهورية الدمنيكان","code":"DMA"},
      {"name":"Stateless XXB","code":"XXB"},
      {"name":"Stateless XXX","code":"XXX"},
      {"name":"Serbia 381","arabicName":"صربيا","code":"SRB"},
      {"name":"Stateless XXA","code":"XXA"},
      {"name":"Liechtenstein","arabicName":"ليختنشتاين","code":"LIE"},
      {"name":"Congo COD","arabicName":"الكنغو","code":"COD"}]`
  );

  module.exports = {nationalities}